electron/chromedriver

.travis.yml
appveyor.yml
download-chromedriver.js
package.json

Seeing `Download failed: invalid distance too far back` errors with the 0.37.x Chromedriver download.
Possibly related to https://github.com/EvanOxfeld/node-unzip/issues/60 to switching to a different unzip module.

Use decompress library instead of unzip

---

README.md
download-chromedriver.js

Small tweak to use the major and minor version values from the local `package.json` instead of only the minor with a hard-coded `0` for the major.

Use major version from package.json

---

README.md
download-chromedriver.js

Adds an `ELECTRON_MIRROR` and `NPM_CONFIG_ELECTRON_MIRROR` env var support to customize where chromedriver is downloaded from.
Follows the lead of [electron-download](https://github.com/electron-userland/electron-download/blob/master/readme.md#usage) 🎩 
Closes https://github.com/electron/electron/issues/6303

Support overriding URL

---

download-chromedriver.js

look for case-sensitive process.env variables as well

OS X is case-sensitive so look for lowercase env variables as well

---

download-chromedriver.js

Use the `npm_config_` proxy configuration environment variables when available and pass through to the request made to download the chromedriver zip.
Closes #8

Support npm proxy config env vars

---

download-chromedriver.js
package.json

Uses electron-download to download chromedriver removing code duplication anding support for progress bar output, caching,  and shasum validation.
Refs https://github.com/electron-userland/electron-download/pull/42

Use electron-download to download Chromedriver

---

chromedriver.js

I started hitting an issue when testing an Electron application using
Spectron where Spectron's `app.start()` promise will never resolve on a
certain Mac Mini test worker, causing my tests to timeout (see related
linked issue in the commit footer).
The problem ended up being that there was a mysterious `chromedriver`
process running on the Mac Mini, bound to port 9515 (the default port).
The following steps led to the problem:
- Spectron ran `electron-chromedriver` using the default port
- `electron-chromedriver` spawned `chromedriver` on 9515, but it
reported success even though `chromedriver` printed the following error
in the background:
```
Starting ChromeDriver 2.27 (44a803957cb27610c38f7e859016ac257959aeb5) on port 9515
Only local connections are allowed.
[0.004][SEVERE]: bind() …
```

fix: check if chromedriver fails to start correctly

---

package.json

We should land https://github.com/electron/chromedriver/pull/39 first

chore: add support for Electron 5 Beta

---

package.json
test/chromedriver-test.js

Update for Electron stable `v6.0.0`.
cc @jkleinsc

chore: add support for Electron v6.0.0

---

.circleci/config.yml
appveyor.yml
download-chromedriver.js
package-lock.json
package.json

Closes #58
Migrates from `electron-download` to `@electron/get`. Biggest motivation: GitHub will give a security warning for any new install of this package due to [a vulnerability with the last `electron-download` version's `minimist` dependency](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7598).
Things to consider:
* The `quiet` and `strictSSL` options are gone. `rejectUnauthorized` seemed like somewhat of an equivalent to the latter. Please correct me if I'm wrong! @cc malept
* Converted callbacks to `async/await` syntax. 
* I snuck in a linting fix command there.
Edit: From discussion below, also:
* Upgraded `extract-zip` to `2.0.0`.
* Forced `node >= 10`

chore: upgrade dependencies to latest

---

download-chromedriver.js

Closes #60 
**Summary**
This PR fixes an issue when trying to install `electron` on a linux machine with environment variable `npm_config_platform=win32`.
**Motivation**
There is support for building electron apps on linux for windows. The `npm_config_platform` is an environment variable that is usually used to instruct npm packages about the platform for which custom or pre-built binaries should be downloaded.   
For example, running: `npm_config_platform=win32 npm i electron-chromedriver` should download the Windows chromedriver.exe even when I run it on a linux machine. This is currently broken and attempting to run it on linux fails with an error.  
There is not much use in downloading the Windows chromedriver on linux. However, if you have a native dependency like …

fix: install npm_config_platform=win32

---

download-chromedriver.js

Found this inconsistency between `electron` and `electron-chromedriver` while investigating https://github.com/electron/get/issues/160
Current `master` (does not set `cacheRoot`, fallback behaviour due to `undefined` cache):
```
$ electron_config_cache=/opt/electron/cache DEBUG=* node ./download-chromedriver.js 
@electron/get:index No platform found, defaulting to the host platform +0ms
@electron/get:index No arch found, defaulting to the host arch +1ms
@electron/get:index Checking the cache (undefined) for chromedriver-v11.0.0-linux-x64.zip (https://github.com/electron/electron/releases/download/v11.0.0/chromedriver-v11.0.0-linux-x64.zip) +1ms
@electron/get:index Cache hit +2ms
extract-zip creating target directory /home/shiftkey/src/chromedriver/bin +0ms
...
```
This PR (sets …

fix: use same settings for force and cacheRoot as electron

---

chromedriver.js

Even though the docs don't seem to suggest that this event's `code` argument can be null. In practice it has the same characteristics as the `"exit"` event.
This package shouldn't throw if the function `killChromeDriver` was called.

fix: don't throw error when code is null

---

README.md
appveyor.yml

This PR changes a few instances (such as AppVeyor) where we were hardcoding the default branch as "master". It should be merged when the branch name is changed to `main`!

chore: update hardcoded master to main

---

.github/workflows/release.yml
package-lock.json
package.json
script/update-version.js

This partially automates the process of releasing new versions of chromedriver when new major releases to Electron occur.
We'll also need to add something like this to the Electron repo itself.
```yml
name: Trigger Major Release Dependency Updates
on:
release:
types: [published]
jobs:
notify:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Trigger New chromedriver Release
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
gh api /repos/:owner/chromedriver/actions/workflows/release.yml/dispatches \
--input - <<< '{"ref":"main","inputs":{"version":"${{ github.event.release.tag_name }}"}}'
```

chore: add release update action

---

.github/workflows/release.yml

Ensures that the correct chromedriver binary is downloaded

ci: bump version before installing dependencies in release workflow

---

script/update-version.js

Test is failing on `main` at the moment due to a rogue semicolon.

chore: remove semicolon to fix linting

---

.circleci/config.yml

We've missed a few of the automated releases by not providing the CFA token in a timely enough manner, as unfortunately the stable builds usually finish at the non-ideal time of lunch time PST. Let's bump the window for providing the token to give ourselves a better chance.

build: bump CFA publish step timeout

---

.circleci/config.yml

Forgot that with the `electronjs/node` orb, `node/test` goes: checkout -> install Node.js -> install packages -> test. So we need to run the steps to set the Electron version to test after installing Node.js but before installing packages.

ci: fix test job on tags

---

.circleci/config.yml

Fixes detecting of failed Node.js installs with `nvm-windows` and bumps the cache version to clear out a corrupted cache as a result of not detecting those failed installs. The cache key does not need to be explicitly bumped because the newest version of the orb changed the cache key format so it effectively changes the cache key.
Also bumps the Node.js v20 version and clears a note regarding that, now that the issue has been fixed upstream.
Refs https://app.circleci.com/pipelines/github/electron/chromedriver/209/workflows/2342bf81-1ee5-49fc-be87-b2901f0431ea/jobs/1079

ci: bump electronjs/node orb version to fix cache issue

---

.github/workflows/release.yml

The default permissions for `GITHUB_TOKEN` appear to have changed on this repo in the past 48 hours, and we weren't explicitly setting write perms before.

ci: add write permission to release job

---

package-lock.json
package.json
test/chromedriver-test.js

This PR modernizes the smoke test in this repo.
* The smoke test was updated to use `@electron/fiddle-core` to map the current version of this package to the matching Chromium release, which is what the `-v` (version) flag outputs
* I noticed that the `semver` dev dep isn't used anywhere, so I took the opportunity to remove it

test: modernize smoke test

---

.circleci/config.yml

Linux CI seems to fail due to missing system dependencies required to load chromedriver, which are added in this PR.

ci: add linux deps

---

.github/workflows/publish-npm.yml

The GH token acquired is only good for 1 hour, and if a maintainer provides a CFA token after that time we end up with the npm publish going through but none of the follow-up steps on GitHub (creating the release).

ci: timeout release job after 1 hour

---

.github/workflows/test.yml
chromedriver.js
download-chromedriver.js
package-lock.json
package.json
script/publish.js
script/update-version.js
test/chromedriver-test.js

Alternative to #157 - we use `prettier` on the majority of our repos and it has no dependencies so let's switch here to simplify.
For now I'm using the `--single-quote` and `--no-semi` options to minimize the diff in this PR. We can drop those in the future to further align the style here with our other repos.

build(dev-deps): switch from standard to prettier
