- chromedriver.js
- download-chromedriver.js
- package-lock.json
- package.json
- test/chromedriver-test.js
Updates to `3.0.0` stable now that `3-0-x` is out of beta. Also ES6-ifies some of the code.
> feat: update to 3.0.0 stable

- download-chromedriver.js
- package-lock.json
- package.json
- test/chromedriver-test.js
Updates standard.js and mocha deps and associated code required by the new major versions.
cc @jkleinsc
> chore: update standard and mocha

- package-lock.json
- package.json
> chore: Update for v7.0.0

- package-lock.json
- package.json
Update for Electron beta v8.0.0-beta.7.
cc @MarshallOfSound
> chore: update for 8.0.0-beta.7

- package-lock.json
- package.json
> chore: upgrade to v8.0.0

- README.md
- package-lock.json
- package.json
> chore: v9.0.0

- package-lock.json
- package.json
> chore: v12.0.0

- package-lock.json
- package.json
Chromedriver for Electron v13.0.0 release.
> chore: 13.0.0

- .circleci/config.yml
Circle will be removing the Xcode 10 image
> build: bump xcode version, 10 is deprecated

- .gitignore
- package.json
Does what it says on the tin - supports Electron 14.
> chore: bump to 14.0.0

- package-lock.json
- package.json
> chore: bump to v15.0.0

- package-lock.json
- package.json
Bumps Chromedriver to 19.0.0
Should be merged after 19.0.0 is released.
> chore: update to v19.0.0

- .circleci/config.yml
> build: update Xcode image on CircleCI

- .github/workflows/release.yml
- .github/workflows/semantic.yml
* Pins SHAs
* Updates `.github/workflows/semantic.yml` to match `e/e`
> build: update GitHub actions workflows

- .circleci/config.yml
These tests run quick, let's test against an expanded matrix.
> build: test against more Node.js versions

- .circleci/config.yml
- .github/workflows/release.yml
- download-chromedriver.js
- package-lock.json
- package.json
- script/publish.js
Same changes as over on `electron/mksnapshot` for CFA releases.
> build: do CFA releases

- download-chromedriver.js
- package-lock.json
- package.json
Same changes as https://github.com/electron/mksnapshot/pull/92.
> chore: use @electron/fiddle-core to get latest stable version

- .circleci/config.yml
Refs https://github.com/electron/github-app-auth/pull/18#pullrequestreview-1746943672
> ci: only exclude 14 on macOS

- .github/workflows/release.yml
Improve the description here so it's self-explanatory for anyone new coming along.
> ci: improve release workflow input description

- script/publish.js
Experiment to see if this works. I believe we meet all the prerequisites listed in https://docs.npmjs.com/generating-provenance-statements now that we publish from GHA.
> ci: publish npm package with provenance statement
